name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        go-version:
          - '1.23'
    runs-on: ubuntu-latest
    steps:
      - name: Check Go Version
        uses: actions/setup-go@v4
        with:
          go-version: ${{matrix.go-version}}
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: builds the code
        run: make build

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.10
      # Install the specific golangci-lint version
      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.64.5/install.sh | sh -s -- -b $GITHUB_WORKSPACE/bin v1.64.5
      - run: $GITHUB_WORKSPACE/bin/golangci-lint run --config integration/golangci-lint.yml ./...
  unittest:
    name: Unit Tests
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - '1.23'
    runs-on: ubuntu-latest
    steps:
    - name: Check Go Version
      uses: actions/setup-go@v4
      with:
        go-version: ${{matrix.go-version}}
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Run tests
      run: make test