name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Extract tool versions
        run: |
          echo "GO_VERSION=$(awk -F ':= ' '/GO_MIN_VERSION/ {print $2; exit}' Makefile)" >> "$GITHUB_ENV"
          echo "LINT_VERSION=$(awk -F ':= ' '/LINT_VERSION/ {print $2; exit}' Makefile)" >> "$GITHUB_ENV"
      - name: Check Go Version
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: builds the code
        run: make build

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Extract tool versions
        run: |
          echo "GO_VERSION=$(awk -F ':= ' '/GO_MIN_VERSION/ {print $2; exit}' Makefile)" >> "$GITHUB_ENV"
          echo "LINT_VERSION=$(awk -F ':= ' '/LINT_VERSION/ {print $2; exit}' Makefile)" >> "$GITHUB_ENV"
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      # Install the specific golangci-lint version
      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/$LINT_VERSION/install.sh | sh -s -- -b $GITHUB_WORKSPACE/bin $LINT_VERSION
      - run: $GITHUB_WORKSPACE/bin/golangci-lint run --config integration/golangci-lint.yml ./...

  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Extract tool versions
        run: |
          echo "GO_VERSION=$(awk -F ':= ' '/GO_MIN_VERSION/ {print $2; exit}' Makefile)" >> "$GITHUB_ENV"
          echo "LINT_VERSION=$(awk -F ':= ' '/LINT_VERSION/ {print $2; exit}' Makefile)" >> "$GITHUB_ENV"
      - name: Check Go Version
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run tests
        run: make test
